/**
 * Token Summary Cards Component
 * Displays high-level aggregated token usage statistics
 */

import { TokenUsageAggregation } from "@/actions/tokenUsage";
import { Card } from "@/components/ui/Card";

interface TokenSummaryCardsProps {
  aggregation: TokenUsageAggregation;
}

export default function TokenSummaryCards({
  aggregation,
}: TokenSummaryCardsProps) {
  const formatNumber = (num: number) => {
    if (num >= 1000000) {
      return `${(num / 1000000).toFixed(2)}M`;
    } else if (num >= 1000) {
      return `${(num / 1000).toFixed(1)}K`;
    }
    return num.toLocaleString();
  };

  // Estimate cost (approximate OpenAI pricing as reference)
  // Input: $0.0015 per 1K tokens, Output: $0.002 per 1K tokens (GPT-4o pricing)
  const estimatedCost =
    (aggregation.totalInputTokens / 1000) * 0.0015 +
    (aggregation.totalOutputTokens / 1000) * 0.002;

  const cards = [
    {
      title: "Total Tokens",
      value: formatNumber(aggregation.totalTokens),
      description: "Combined input + output",
      icon: "📊",
    },
    {
      title: "Input Tokens",
      value: formatNumber(aggregation.totalInputTokens),
      description: "Tokens sent to LLM",
      icon: "📤",
    },
    {
      title: "Output Tokens",
      value: formatNumber(aggregation.totalOutputTokens),
      description: "Tokens generated by LLM",
      icon: "📥",
    },
    {
      title: "Total Requests",
      value: aggregation.totalRequests.toLocaleString(),
      description: "API calls made",
      icon: "🔄",
    },
    {
      title: "Estimated Cost",
      value: `$${estimatedCost.toFixed(2)}`,
      description: "Based on GPT-4o pricing",
      icon: "💰",
    },
  ];

  return (
    <div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-5">
      {cards.map((card, index) => (
        <Card key={index} className="p-6">
          <div className="flex items-start justify-between">
            <div className="flex-1">
              <p className="text-sm font-medium text-gray-600 dark:text-gray-400">
                {card.title}
              </p>
              <p className="mt-2 text-3xl font-semibold text-gray-900 dark:text-white">
                {card.value}
              </p>
              <p className="mt-1 text-xs text-gray-500 dark:text-gray-500">
                {card.description}
              </p>
            </div>
            <span className="text-2xl">{card.icon}</span>
          </div>
        </Card>
      ))}
    </div>
  );
}
